// Generated by CoffeeScript 1.6.1
var $, Gakugaku,
  _this = this;

$ = jQuery;

Gakugaku = (function() {

  Gakugaku.prototype.shake = function(obj) {
    var r, xpos, ypos;
    xpos = (Math.random() - 0.5) * this.xdepth;
    ypos = (Math.random() - 0.5) * this.ydepth;
    r = (Math.random() - 0.5) * this.tilt;
    return obj.transition({
      rotate: r + 'deg',
      x: xpos + 'px',
      y: ypos + 'px'
    });
  };

  function Gakugaku() {
    var base, container, msgary, spans, vars,
      _this = this;
    this.shake = function(obj) {
      return Gakugaku.prototype.shake.apply(_this, arguments);
    };
    vars = getUrlVars();
    if (!("m" in vars)) {
      $("#divBase").hide();
      return false;
    }
    $("#divForm").hide();
    this.msg = decodeURIComponent(vars["m"]);
    this.size = vars["s"] + "px";
    this.spacing = parseFloat(vars["p"]);
    this.fgcolor = decodeURIComponent(vars["c"]);
    this.bgcolor = decodeURIComponent(vars["b"]);
    this.xdepth = parseFloat(vars["x"]);
    this.ydepth = parseFloat(vars["y"]);
    this.tilt = parseFloat(vars["r"]);
    this.frequency = parseFloat(vars["f"]) * 1000;
    msgary = this.msg.split("");
    base = $("#divBase");
    base.css("background-color", this.bgcolor);
    base.css("color", this.fgcolor);
    base.css("font-size", this.size);
    container = $("#divContainer");
    $.each(msgary, function(idx, str) {
      var span;
      span = $("<span>" + str + "</span>");
      return container.append(span);
    });
    spans = container.find("span");
    spans.css("margin-right", this.spacing + "px");
    spans.each(function(idx, obj) {
      return setInterval(function() {
        return _this.shake($(obj));
      }, _this.frequency);
    });
  }

  return Gakugaku;

})();

$(function() {
  $.fx.speeds._default = 0;
  return Gakugaku = new Gakugaku;
});
